<?php

/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use Yii;
use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{

    public $basePath = '@webroot';
    public $baseUrl = '@web';

    //add to github
    public $css = [];
    public $js = [];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public $publishOptions = [
        'forceCopy' => true
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $assests = Yii::$app->assetManager;

        if (\Yii::$app->controller->action->id == 'post') {
            $this->js[] = 'css/editor/js/froala_editor.min.js';
            $this->js[] = 'css/editor/js/froala_editor.min.js';
            $this->js[] = 'css/editor/js/plugins/char_counter.min.js';
            $this->js[] = 'css/editor/js/plugins/video.min.js';
            $this->css [] = 'css/font-awesome/css/font-awesome.min.css';
            $this->css [] = "css/editor/css/froala_editor.min.css";
            $this->css [] = "css/editor/css/froala_style.min.css";
            if (Yii::$app->language == 'ar')
                $this->js[] = 'css/editor/js/langs/ar.js';
        }

        if (Yii::$app->language == 'en') {
            $assests->assetMap['bootstrap.css'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css';
            //$assests->assetMap['bootstrap.js'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js';

            $this->css [] = YII_DEBUG ? 'css/site.en.css' : 'css/site.en.min.css';
        } else {
            $this->css [] = YII_DEBUG ? 'css/site.css' : 'css/site.min.css';
        }

        $this->js[] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js';

        $this->css [] = 'css/font-awesome/css/font-awesome.min.css';
        $this->js[] = YII_DEBUG ? 'js/main.js' : '/js/main.1.1.min.js';

    }
}
