<?php

/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use Yii;
use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{

    public $basePath = '@webroot';
    public $baseUrl = '@web';

    //add to github
    public $css = [];
    public $js = [];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public $publishOptions = [
        'forceCopy' => true
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $assests = Yii::$app->assetManager;

        if (\Yii::$app->controller->action->id == 'post') {

            //old
            $this->js[] = 'css/editor/js/froala_editor.min.js';
            $this->js[] = 'css/editor/js/froala_editor.min.js';
            $this->js[] = 'css/editor/js/langs/ar.min.js';
            $this->js[] = 'css/editor/js/plugins/char_counter.min.js';
            $this->js[] = 'css/editor/js/plugins/video.min.js';
            $this->css[] = 'css/font-awesome/css/font-awesome.min.css';
            $this->css[] = "css/editor/css/froala_editor.min.css";
            $this->css[] = "css/editor/css/froala_style.min.css";
            //old


            $this->js[] = 'medium/js/jquery.ui.widget.js';
            $this->js[] = 'medium/js/jquery.iframe-transport.js';
            $this->js[] = 'medium/js/jquery.fileupload.js';
            $this->js[] = 'medium/js/medium-editor.js';
            $this->js[] = 'medium/js/medium-editor-handsontable.js';
            $this->js[] = 'medium/js/handlebars.runtime.min.js';
            $this->js[] = 'medium/js/jquery-sortable-min.js';
            $this->js[] = 'medium/js/jquery.cycle2.min.js';
            $this->js[] = 'medium/js/jquery.cycle2.center.min.js';


            $this->js[] = 'medium/js/medium-editor-insert-plugin.js';

            $this->css [] = "medium/css/medium-editor.css";
            $this->css [] = "medium/css/themes/default.min.css";
            $this->css [] = "medium/css/medium-editor-insert-plugin.min.css";


//            $this->js[] = 'css/editor/js/froala_editor.min.js';
//            $this->js[] = 'css/editor/js/plugins/char_counter.min.js';
//            $this->js[] = 'css/editor/js/plugins/video.min.js';
            if (Yii::$app->language == 'ar') {
//                $this->js[] = 'css/editor/js/langs/froala_editor_ar.js';
                $this->js[] = 'https://s3.amazonaws.com/hangshare.static/assets/ar.min.js';
            }
            $this->css [] = 'css/font-awesome/css/font-awesome.min.css';
//            $this->css [] = "css/editor/css/froala_editor.min.css";
//            $this->css [] = "css/editor/css/froala_style.min.css";
        }

        if (Yii::$app->language == 'en') {
            $assests->assetMap['bootstrap.css'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css';
            //$assests->assetMap['bootstrap.js'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js';
            $this->css [] = YII_DEBUG ? 'css/site.en.css' : 'css/site.en.min.css';
        } else {
            $this->css [] = YII_DEBUG ? 'css/site.css' : 'css/site.min.css';
        }

        $this->js[] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js';
        $this->css [] = 'css/font-awesome/css/font-awesome.min.css';
        $this->js[] = "js/jquery.viewportchecker.js";
        $this->js[] = "flot/jquery.flot.js";
        $this->js[] = "flot/jquery.flot.pie.js";
        $this->js[] = 'js/jq-ui.js';
        $this->css [] = "css/animate.min.css";
        $this->js[] = "Volar_files/wow.js";
        $this->css [] = "owl/owl.carousel.css";
        $this->css [] = "owl/owl.theme.css";
        $this->js[] = "owl/owl.carousel.js";
        $this->js[] = YII_DEBUG ? 'js/main.js' : '/js/main.1.2.min.js';

        $this->js[] = 'https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js';
    }
}
