<?php


namespace app\models;

use Yii;


/**
 * This is the model class for table "post".
 *
 * @property integer $id
 * @property string $name
 * @property string lang
 * @property int published
 */
class Tags extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tags';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['lang'], 'string', 'max' => 2],
            [['published'], 'integer'],
            [['name'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Tags.id'),
            'name' => Yii::t('app', 'Tags.tagN+ame'),
        ];
    }

    public function beforeSave($insert)
    {
        $this->lang = Yii::$app->language;
        $this->published = 0;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
